Adição de método para obter periodicidade da Série
ufla-ppoo/Series-de-Dados pull request #8
Opened 2023-02-25 16:53 UTC by IsraelSantosV

Nessa solução, foi criado um enumerável que representa uma determinada periodicidade. Além disso, dentro da SerieDados foi criado um método para obter a periodicidade. Os nomes de dias também foram alterados para ficarem coesos.

2023-02-26 14:28 UTC, caburu requested changes
Olá @IsraelSantosV, obrigado por enviarem o Pull Request.

A proposta feita é muito boa. Envio alguns comentários para torná-la melhor, especialmente, para o entendimento dos alunos que fizerem os exercícios.

Além dos comentários abaixo, lembrem-se que é necessário **alterar também o README.md**  do projeto. Vejam que os enunciados dos exercícios falam que a série é por dia (especialmente nos Passos 1, 3 e 5), mas, com as alterações desse Pull Request, o enunciado tem que ser adaptado ao novo código.

Muito obrigado pelas contribuições e estou à disposição em caso de qualquer dúvida.

2023-02-26 14:28 UTC, caburu commented on src/series/Periodicidade.java
> +
Seria interessante que os valores de periodicidade fossem dados por adjetivos (ficaria mais claro) e, para seguir a convenção da programação em Java, fossem escritos com letras maiúsculas (ex: `HORARIA`, `DIARIA`, etc.).
- Sugiro também acrescentar as opções: `MENSAL` e `POR_EVENTO` e remover a opção `Inteiro`.

2023-02-26 14:28 UTC, caburu commented on src/series/SerieDados.java
> + * Assim podemos ter dados, por exemplo, do valor 5 ao valor 30.
Usar o termo _valor_ para periodicidade pode confundir os alunos na hora de fazer o exercício. Já que eles podem associar o termo _valor_ com os dados que estão sendo armazenados e não não com a periodicidade.
- Vejam que os nomes dos métodos `obterInicioPeriodo` e `obterFimPeriodo` deixam claro que se referem à periocidade. Dessa forma, todos os comentários também deveriam seguir a mesma linha.
- Além disso, é necessário acrescentar a explicação sobre o `enum` Periodicidade.

Assim, o trecho destacado, por exemplo, ficaria mais claro se fosse algo como:

> Uma série de dados tem uma periodicidade, um intervalo (dado por um período inicial e um final) e valores inteiros (dados) correspondentes a cada período.
> 
> A periodicidade pode ser, por exemplo, horária, diária, semanal, etc. Já os períodos, por simplicidade, são dados por números inteiros.
> - Exemplo: suponha que a série tenha periodicidade horária, e o período inicial seja 7 e o final 12. Isso significa que a série terá dados de hora em hora a partir das 7h até às 12h.

2023-02-26 14:28 UTC, caburu commented on src/series/SerieDados.java
> +     * @return O primeiro valor que possui dados.
Como falado no comentário anterior, lembrem-se de alterar todos os locais (não só esse) que tinham sido alterados de _dia_ para _valor_, passando a deixar claro que se refere a _período_.

2023-02-26 14:28 UTC, caburu commented on src/series/VisualizadorSeries.java
> +           for(int valor = serie.obterInicioPeriodo(); valor <= serie.obterFimPeriodo(); valor++) {
Melhor usar `periodo` em vez de `valor`.

2023-02-26 15:26 UTC, IsraelSantosV commented
Realizei o commit das correções.

2023-02-27 11:04 UTC, caburu approved these changes
Ótimo! Muito obrigado pelas contribuições!

2023-02-27 11:04 UTC, merged